### ISSUE TITLE
How to modify the settings?

### ISSUE THREAD

**Issue by pseudokawaii** [txchen/xbrowsersync-cfw#1]
It would be very helpful if you could elaborate on how to modify the settings properly. Especially for people who are not very familiar with JavaScript or xBrowserSync like me.

There's one other thing, is it possible to show a status page like this in the worker?

![image](https://user-images.githubusercontent.com/63403140/122667503-f3e3da00-d1d4-11eb-999b-164aa536d024.png)

**Comment by txchen** [comment]
To modify the setting: directly modify the Javascript file (index.js) in cloudflare UI.

Web page is not available, but you can see the version and status in xBroswerSync browser extension, if connected successfully.
