### ISSUE TITLE
xBrowserSync Android client refuses to connect to routed Cloudflare Worker

### ISSUE THREAD

**Issue by crlmahlberg** [txchen/xbrowsersync-cfw#4]
First of all, thanks for allowing me to set up the xBrowserSync API as a Cloudflare Worker. The API is now accessible from a URL like https://xbrowsersync.example.workers.dev. That worked as expected for the official Chrome extension as well as for the official Android app. Now to my actual issue: What I want is to create a _route_ (https://developers.cloudflare.com/workers/platform/routes) so that the API is accessible from a URL like https://xbrowsersync.example.com. I set up everything as described in the aforementioned document and the Chrome extension connects to the routed Worker just fine, but the Android client refuses, giving me a **HttpRequestFailed** error. Do you have any idea why this is? I googled for hours without finding any clues. Thanks in advance for your help!

**Comment by txchen** [comment]
I have never tried cf route and android client, and I have no idea why chrome ext can work but android cannot. 
Have you tried using curl to call the api to debug? Most likely I guess it is android client's issue, maybe to get more detailed log from it?

**Comment by crlmahlberg** [comment]
You're right, there seems to be an issue with the Android client, as reported in https://github.com/xbrowsersync/app/issues/284. I figured out a solution by deleting the Cloudflare route and creating a simple reverse proxy on my web server instead. Cloudflare is then used only for DNS, not as a proxy (grey, not orange cloud), otherwise the Android client won't connect to the API.
